name:                rwh-exercises
version:             0.1.0.0
github:              "tuxxi/real_world_haskell"
license:             BSD3
author:              "tuxxi"
maintainer:          "aidan@sojourner.me"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rwh-exercises#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -O
- -Wno-unused-top-binds
- -Wno-missing-signatures

executables:
  ch03:
    main:           Main.hs
    source-dirs:    src/ch03

  ch04:
    main:           InteractWith.hs
    source-dirs:    src/ch04